### ISSUE TITLE
macOS investigation

### ISSUE THREAD

**Issue by simonjwright** [pyjarrett/trendy_terminal#3]
Well, I just have to try macOS!

Looking at `trendy_terminal-linux.ads`, I think the treatment of `c_lflag_t` and `Local_Flags` is confusing if not wrong.

The representations of `c_lflag_t` (which are mask values) look as thought they ought to be octal, not hex? (values 1, 2, 4, 10 ...) - but  `Local_Flags` is an array indexed by the position, not the representation, so that `ECHO` is bit 3, as it should be (on Linux).

On macOS, things are different (order, missing values):
```
    for c_lflag_t use
      (
       ECHOKE     => 16#00000001#,
       ECHOE      => 16#00000002#,
       ECHOK      => 16#00000004#,
       ECHO       => 16#00000008#,
       ECHONL     => 16#00000010#,
       ECHOPRT    => 16#00000020#,
       ECHOCTL    => 16#00000040#,
       ISIG       => 16#00000080#,
       ICANON     => 16#00000100#,
       ALTWERASE  => 16#00000200#,
       IEXTEN     => 16#00000400#,
       EXTPROC    => 16#00000800#,
       TOSTOP     => 16#00400000#,
       FLUSHO     => 16#00800000#,
       NOKERNINFO => 16#02000000#,
       PENDIN     => 16#20000000#,
       NOFLSH     => 16#80000000#
      );
```
I know we don’t use the last 4, so we could use the current scheme, but I’ve seen a `NOKERNINFO` in the wild. I’ve gone for e.g. in `Set`
```
        case Setting is
           when Platform.Echo =>
               Std_Input.Settings.c_lflag :=
                 Std_Input.Settings.c_lflag and not Macos.ECHO'Enum_Rep;
               if Enabled then
                   Std_Input.Settings.c_lflag :=
                     Std_Input.Settings.c_lflag or Macos.ECHO'Enum_Rep;
               end if;
```

Anyway, I spent a _long_ time before noticing that `termios.h` says
```
typedef unsigned long   tcflag_t;
typedef unsigned char   cc_t;
typedef unsigned long   speed_t;
```
and on macOS `unsigned long` is 8 bytes, so the Ada has to be `unsigned_long`:
```
    NCCS : constant := 20;
    type tcflag_t is new Interfaces.C.unsigned_long;
    type cc_t is new Interfaces.C.unsigned_char;
    type speed_t is new Interfaces.C.unsigned_long;
    type cc_array is array (Natural range 0 .. NCCS - 1) of cc_t;
```

On macOS, I couldn't say
```
    stdin  : aliased FILE_Ptr;
    stdout : aliased FILE_Ptr;
    stderr : aliased FILE_Ptr;

    pragma Import (C, stdin, "stdin");
    pragma Import (C, stdout, "stdout");
    pragma Import (C, stderr, "stderr");
```
because the symbol `_stdin` (I _think_ the underscore was there). After delving into the GNAT runtime, I came up with
```
    function Gnat_Constant_Stdin return FILE_Ptr with
        Import        => True,
        Convention    => C,
        External_Name => "__gnat_constant_stdin";
    function Gnat_Constant_Stdout return FILE_Ptr with
        Import        => True,
        Convention    => C,
        External_Name => "__gnat_constant_stdout";
    function Gnat_Constant_Stderr return FILE_Ptr with
        Import        => True,
        Convention    => C,
        External_Name => "__gnat_constant_stderr";

    stdin  : aliased FILE_Ptr := Gnat_Constant_Stdin;
    stdout : aliased FILE_Ptr := Gnat_Constant_Stdout;
    stderr : aliased FILE_Ptr := Gnat_Constant_Stderr;
```
(ugh)

**Comment by pyjarrett** [comment]
Thanks for the help! 

I normally don't develop on Mac, but had been messing around a little with this a few nights ago by happenstance.

🎉 This gets me to working Mac support in the branch I'm on! 🎉 

> I think the treatment of c_lflag_t and Local_Flags is confusing if not wrong.
>
> Local_Flags is an array indexed by the position, not the representation

I was expecting representation, but must not have checked.  It's wrong, I was using a language feature which I thought gave a different behavior.  I just added padding bits, maybe I should have gone with my original idea of just using a modular type?

> On macOS, I couldn't say

The symbols on Mac are preprocessors to different representations:

```
    pragma Import (C, stdin, "__stdinp");
    pragma Import (C, stdout, "__stdoutp");
    pragma Import (C, stderr, "__stderrp");
```

I'll post an updated trendy_terminal with these fixes/changes, and now Mac support, later this week.

**Comment by pyjarrett** [comment]
Thanks for the help, changes are in 0.0.5.

- f56da7f18a8ad2c4be12501aa8f31d2aad8f6095
- d51b10758fa91d62bc15a7535fe6c2fbda4e7d5f
- b37259f18e9bece10d35500a9d56513de3a2b79e
